version: '3.8'

services:
  # Сервис для Node.js сервера
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - HOST=0.0.0.0  # Теперь сервер слушает все сети
      - PORT=6000
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:241111@db:5432/vka_chat  # Подключение к БД внутри Docker
    depends_on:
      - db
    restart: always  # Автостарт при сбое
    networks:
      - vka-chat-network

  # Сервис для PostgreSQL
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=241111
      - POSTGRES_DB=vka_chat
      - TZ=Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./query_new.sql:/docker-entrypoint-initdb.d/query_new.sql
    restart: always  # Автостарт при сбое
    networks:
      - vka-chat-network

  # Сервис для pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    depends_on:
      - db
    restart: always  # Автостарт при сбое
    networks:
      - vka-chat-network

volumes:
  pgdata:

networks:
  vka-chat-network:
    driver: bridge
